package com.siu.android.tennisparis.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AVAILABILITY.
 */
public class Availability implements java.io.Serializable {

    private Long id;
    private java.util.Date day;
    private Integer hour;
    private String ground;
    private Long webserviceTennisId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Availability() {
    }

    public Availability(Long id) {
        this.id = id;
    }

    public Availability(Long id, java.util.Date day, Integer hour, String ground, Long webserviceTennisId) {
        this.id = id;
        this.day = day;
        this.hour = hour;
        this.ground = ground;
        this.webserviceTennisId = webserviceTennisId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDay() {
        return day;
    }

    public void setDay(java.util.Date day) {
        this.day = day;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public String getGround() {
        return ground;
    }

    public void setGround(String ground) {
        this.ground = ground;
    }

    public Long getWebserviceTennisId() {
        return webserviceTennisId;
    }

    public void setWebserviceTennisId(Long webserviceTennisId) {
        this.webserviceTennisId = webserviceTennisId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
