package com.siu.android.tennisparis.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table TENNIS.
 */
public class Tennis implements java.io.Serializable {

    private Long id;
    private Long webserviceId;
    private String name;
    private String address;
    private String postalCode;
    private String city;
    private Double latitude;
    private Double longitude;
    private Boolean active;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Tennis() {
    }

    public Tennis(Long id) {
        this.id = id;
    }

    public Tennis(Long id, Long webserviceId, String name, String address, String postalCode, String city, Double latitude, Double longitude, Boolean active) {
        this.id = id;
        this.webserviceId = webserviceId;
        this.name = name;
        this.address = address;
        this.postalCode = postalCode;
        this.city = city;
        this.latitude = latitude;
        this.longitude = longitude;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getWebserviceId() {
        return webserviceId;
    }

    public void setWebserviceId(Long webserviceId) {
        this.webserviceId = webserviceId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    // KEEP METHODS - put your custom methods here
    public String getFullAddress() {
        return address + ", " + postalCode;
    }
    // KEEP METHODS END

}
